services:
  database:
    image: mysql:8.4.0
    restart: always
    container_name: database
    environment:
       MYSQL_DATABASE=""
       MYSQL_USER="user"
       MYSQL_PASSWORD="password"
       MYSQL_ROOT_PASSWORD="password"
    ports:
      - 3306:3306
    volumes:
      - .starter-kit-db:/var/lib/mysql
    networks:
      - app_next
networks:
  app_next:
    driver: bridge
volumes:
  .starter-kit-db: